### ISSUE TITLE
`ably` dependency is very large when bundled

### ISSUE THREAD

**Issue by SimonSchick** [magicbell-io/magicbell-core#8]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/3259089/179034099-f7b53a35-e73e-41bc-995f-41f5d1ffd6d1.png">

This is currently really inflating our bundle size, can you do something to reduce it's usage?

**Comment by smeijer** [comment]
We're moving to a mono-repo, and thereby I'm closing this issue. 

Unfortunately, we can't do much about the ably size. That being said, as this package is designed to run on the server, I'm also not sure if it's really that much of an issue. 500k extra for a server deployment ain't that much.

If you think otherwise, please create a new issue on https://github.com/magicbell-io/magicbell-js.
